dist: trusty
sudo: false
language: node_js
node_js:
  - '6'
addons:
  chrome: stable
before install:
    - rvm install 2.2
before_script:
  - gem install sass compass
  - npm install -g bower grunt-cli
  - npm install
  - bower install
