dist: trusty
sudo: false
language: node_js
node_js:
  - '8'
addons:
  chrome: stable
before install:
    - rvm install 2.2
before_script:
  - gem install sass compass
  - npm install -g bower grunt-cli
  - npm install
  - bower install
before_deploy:
    grunt build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
